server:
  port : ${PORT:8081}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/currency_db}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/prove}
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
currency:
  url: https://api.apilayer.com/exchangerates_data/convert
  apiKey: ${API_KEY:Tan1rLeMHLNa1kBHq37GvVukmLF7bFDY}

logging:
  level:
    org.springframework.security: DEBUG

token:
  converter:
    principal-attribute: preferred_username
    resource-id: ${RESOURCE_ID:backend_client}